### ISSUE TITLE
activate_driver.sh fails

### ISSUE THREAD

**Issue by RafTim** [pez2001/razer_blackwidow_chroma_driver#1]
I executed activate_driver.sh and got following Error:

./activate_driver.sh    

make -C /lib/modules/3.18.6-1-ARCH/build SUBDIRS=/home/localuser/git/razer_blackwidow_chroma_driver/driver all
make[1]: Entering directory '/usr/lib/modules/3.18.6-1-ARCH/build'
scripts/Makefile.build:44: arch/x86/boot/Makefile: No such file or directory
make[2]: *** No rule to make target 'arch/x86/boot/Makefile'.  Stop.
arch/x86/Makefile:230: recipe for target 'bzImage' failed
make[1]: *** [bzImage] Error 2
make[1]: Leaving directory '/usr/lib/modules/3.18.6-1-ARCH/build'
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 2
insmod: ERROR: could not load module driver/razerkbd.ko: No such file or directory

**Comment by pablomenino** [comment]
See the file
Makefile
You have this line on it:
make -C $(KERNELDIR) SUBDIRS=$(DRIVERDIR) **all**

change this line for:
make -C $(KERNELDIR) SUBDIRS=$(DRIVERDIR) **modules**

I try this on Fedora 21 and works fine.
