### ISSUE TITLE
So nice

### ISSUE THREAD

**Issue by steebchen** [pez2001/razer_blackwidow_chroma_driver#10]
You did a really god job. This is so nice, where can I donate?
I'm also thinking of writing a small program when I find a bit time (will not be a real GUI, but a small program in the command line which asks you question and so on, will be as simple as possible) where you can save static colors for each key or several keys (you can select a color, press keys which should have this color and then save or even select predefined key groups like num block or letters). I *eventually* add other effects like another color while clicking, transitions and fading etc.

By the way, is there a keycode for the razer symbol on the bottom?

**Comment by pez2001** [comment]
Everybody likes recognition of his work , so donations are very welcome in that way :-)
This is a real nice gesture and i would like to add you to the project donators list in the readme
(only if you want that of course)
You can send your donation to: feckelburger@gmx.net via PayPal
(it will be put into a fund for a razer mouse to test multi device setups)
Code contributions are also very welcome.

The logo is oddly placed at 20,0 (column,row) i enhanced to dota_keys example to show it.

Best greets and i hope you have fun with driver/tools.
