### ISSUE TITLE
Getting a list to translate keys to pos.x and pos.y

### ISSUE THREAD

**Issue by TheKiwi5000** [pez2001/razer_blackwidow_chroma_driver#11]
Hi!
I just started messing around with the library, and i am trying to light up the Ctrl, Alt, and Shift keys.
`razer_convert_ascii_to_pos` works just fine for setting letter keys, but how can i set the ctrl key? it's not in the ascii table.

Can you create a file in the repo that lists x-y pairs to keys?

**Comment by pez2001** [comment]
Hi!
You can use:
void razer_convert_keycode_to_pos(int keycode,struct razer_pos *pos);
determine the position of the ctrl,alt and other non letter keys.
You can look at the function to determine the values you have to use, or use some other lists where keycodes are noted like: http://www.comptechdoc.org/os/linux/howlinuxworks/linux_hlkeycodes.html
