### ISSUE TITLE
Combining effect modes

### ISSUE THREAD

**Issue by graywizardx** [pez2001/razer_blackwidow_chroma_driver#13]
Is it possible to combine effect modes from the scripts in the drivers directory?

For instance I would like to have set_spectrum.sh run, and then run set_reactive.sh 255 0 0 to make the key I typed highlight red but still have the spectrum effect going.

Looking at the templates on the chroma site it appears possible, but I am not sure how its done.

**Comment by pez2001** [comment]
These are internal effects that run in the keyboard mcu so its not possible to alter them easily,
someone could reimplement them in software(daemon effect plugin) and mix them using the daemon though.
