### ISSUE TITLE
makefile doesn't work with archlinux

### ISSUE THREAD

**Issue by elKokito** [pez2001/razer_blackwidow_chroma_driver#14]
`sudo make -s all install` return with `Makefile:7: recipe for target 'razer_kdb' failed`, any idea what is going wrong?

**Comment by carstene1ns** [comment]
You need to provide more output, the real error is above in the build log.
A random guess: Did you install [`linux-headers`](https://www.archlinux.org/packages/core/x86_64/linux-headers/) package?

**Comment by elKokito** [comment]
well I have now, error I get is
`chown: cannot access '/etc/init.d/razer_bcd': Not a directory`
and having a look at `/etc/init.d` it's a shell script, not a directory, and it's generated by
the makefile. do you need all the output from the `sudo make -S all install`?

**Comment by carstene1ns** [comment]
Arch Linux does not use SysV init, so the directory does not exist. The Makefile now copies the init script to the non-existent directory and creates a file with the same name instead. If you want to use the Makefile, you need to create it yourself before.
However, note that you need to start the daemon yourself, even if the script exists.

**Comment by Flennic** [comment]
Hello everybody,

I have exactly the same problem but due to missing knowledge I am unable to to solve the issue myself. It'd be great if there were a makefile which works with Arch Linux. Is there anyone around who is able to do that? If there is any way to help, I'd do that.

**Comment by terrycain** [comment]
I've not forgotten about you guys. Currently debugging some usb stuffs, Have a distro based on arch in a vm so testing it is on my list of things to do.

**Comment by Flennic** [comment]
Hi terrycain,

glad to hear that. Just got my Keyboard today :-)
If there is anything to help let me know!

**Comment by terrycain** [comment]
See #37, has fix. Well it fixes Manjaro which seems to be an arch derivative, so try that.
