### ISSUE TITLE
write permissions to repo

### ISSUE THREAD

**Issue by jamesshawver1** [pez2001/razer_blackwidow_chroma_driver#16]
Is there any chance I could get write permission to your repo? I managed to create a profile from your driver that I think people would like to use. It essentially is a non-collision detecting version of the old game "Snake".

**Comment by pez2001** [comment]
sorry for replying this late but i was on vacation.
i will look into your source (manual pull and reduce redundancies) but i will add your example and credit you for it, thats promised.
best greets and keep on the good work ;-)

tim

**Comment by pez2001** [comment]
added snake, nice and funny addition, minor makefile polishing done. thanks again for your contribution, and i hope to see other stuff from you.

**Comment by jamesshawver1** [comment]
not a problem :) thanks to you for doing all the heavy lifting
