### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by itamblyn** [pez2001/razer_blackwidow_chroma_driver#18]
I tried this on xubuntu 15.04 and it does not seem to work.

Is there an uninstall script?

**Comment by pez2001** [comment]
not atm, try sudo make uninstall

2015-09-14 19:13 GMT+02:00 Isaac Tamblyn <notifications@github.com>:

> I tried this on xubuntu 15.04 and it does not seem to work.
>
> Is there an uninstall script?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pez2001/razer_blackwidow_chroma_driver/issues/18>.
>



-- 
The NSA verified this email and as such it is regarded to be spam and virus
free
