### ISSUE TITLE
Some modes not working on BlachWidow Chroma Tournament Edition

### ISSUE THREAD

**Issue by dubbleohnexus** [pez2001/razer_blackwidow_chroma_driver#39]
I was very excited to get this working, but to my (non)surprise several modes did not work while others worked perfectly.

# Modes that worked
* Mode_game
* Mode_none
* Mode_spectrum
* Mode_wave

# Modes that did not work
* Mode_breath
* <s>Mode_custom (just went blank, not sure if theres something else i had to do)</s>
* <s>Mode_reactive</s>
* <s>Mode_static</s>

The modes that did not work seem to all be ones that might require some kind of extra configuration, is it possible that I just missed something in my reading? How could I test if these really do not work or if I'm just not getting something?

OS: Xubuntu 3.19.0-33-generic
Keyboard: Razer Blackwidow Chroma Tournament Edition

Also interesting was that device_type was missing.

**Comment by dubbleohnexus** [comment]
After messing around with the wiki more, I found that reactive mode does work, while breathing mode still does not. I havent touched custom mode or static mode again, but i will report back shortly

**Comment by terrycain** [comment]
@dubbleohnexus Breathing mode needs to be patched, am waiting on a pull request.

**Comment by lah7** [comment]
Can confirm **Breath Mode** isn't working on the Razer BlackWidow Chroma (`RZ03-0122`)

**Comment by terrycain** [comment]
Breath mode now works. Closed
