### ISSUE TITLE
"razer_drv" compile fails when working directory path contains spaces.

### ISSUE THREAD

**Issue by lah7** [pez2001/razer_blackwidow_chroma_driver#53]
Running Ubuntu MATE 15.10 (amd64) here, I've noticed that `make -s all` will fail to compile when the path to my working directory contains spaces.

This is the last few lines leading up to the error:
<pre>:: COMPILING snake game
======================
 
 :: COMPILING dynamic
======================

:: COMPILING razer kernel modules
========================================
Makefile:9: recipe for target 'razer_drv' failed
make: *** [razer_drv] Error 2</pre>

The directory is `/media/Data/Programming/Open Source/BlackWidow Chroma Driver/razer_blackwidow_chroma_driver` - Note spaces in the path.

If I compile from `/tmp/razer_blackwidow_chroma_driver`, no errors occur.

**Comment by terrycain** [comment]
Make doesn't handle spaces well at all. It would require some major hack to fix that which would just fill the Makefile with rubbish. Just don't have spaces in the path.

**Comment by lah7** [comment]
I see, we ought to note that in the README to avoid anyone else getting the same error.

**Comment by terrycain** [comment]
You can create a Wiki page ;-). I feel we should have one for troubleshooting common issues. And possibly one for guidelines for submitting bugs, so we don't end up with people saying "It doesn't work"

**Comment by Yasgur99** [comment]
I am in a path that does not have spaces, yet I get the same error

**Comment by terrycain** [comment]
Do you have the correct kernel headers installed?

**Comment by Yasgur99** [comment]
how do I tell?? @terrycain

**Comment by terrycain** [comment]
What distribution are you using?

**Comment by Yasgur99** [comment]
ubuntu 16.04.1

**Comment by terrycain** [comment]
You using code from my fork or from this repo?
