### ISSUE TITLE
Cant get this running on my linux box. 

### ISSUE THREAD

**Issue by InfiniteDevelopment** [pez2001/razer_blackwidow_chroma_driver#7]
This is made for linux correct?

**Comment by pez2001** [comment]
correct

**Comment by pez2001** [comment]
and what is your problem if i may ask ?

**Comment by kitsuneplusplus** [comment]
Hey! I'm having an issue getting this to run on my Ubuntu Mate installation. I'm pretty familiar with C, so I did like 2 hours of toying around with it, but was still unable to get it working. My problem is that on compilation, I receive an "undefined reference to atan2" error. My natural response was just in case to manually -lm all of the compilation lines, this presented more errors (which I unnecessarily fixed lol) which brought me back to the undefined atan2 reference. Any help would be much appreciated! I think the error throws on the debug files being compiled. Please help :3 I love pretty colors on my keyboard.

**Comment by InfiniteDevelopment** [comment]
Same here, I am using the Ubuntu 14.04 distro, its not lighting up at all after following the build steps.

**Comment by kitsuneplusplus** [comment]
hey InfiniteDevelopment, try downloading the newest update of the driver. Make sure to clean out any old stuff. Then, instead of running the original install script, run the new debian_install.sh script. It fixed it for me.
