### ISSUE TITLE
Getting Scripts to Persist

### ISSUE THREAD

**Issue by kitsuneplusplus** [pez2001/razer_blackwidow_chroma_driver#8]
Okay! I replied to the other issue just to get your attention. I've now got the driver installed on my machine thanks to the new debian install script. I have working lights and my keyboard is currently on a red fade. I went through your dota layout tutorial and compiled it. It works, but only for a second. (it flashes that layout for like one moment, but stays red fade). How do I get it to "stick" with that layout instead of the red one? So far I've tried adding an infinite while loop, but that just made it flash the red layout a bunch. I assume there's a way to push the layout you want to use to the razer_bcd executable, but I'm not sure how? I know you're busy, and I really appreciate all the work you've done on this so far, it really is fantastic. Any help would be much appreciated!

--
shibumi-xx

**Comment by pez2001** [comment]
the dota layout is updating the keyboard just once and the razer_bcd overwrites it immediately.
One simple solution at the moment would be to disable the daemon by calling /etc/init.d/razer_bcd stop

A better solution would be to integrate a keyboard layout effect to be included with the daemon (work to be done).
